<?php

namespace AppBundle\Repository;

/**
 * HistoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
