<?php

namespace AppBundle\Repository;

/**
 * ProduktyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduktyRepository extends \Doctrine\ORM\EntityRepository
{
}
